### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jstasiak** [mozilla/sphinx-js#226]
Hey all,

Thank you for a great project, it's a nice addition to the Sphinx ecosystem.

I'm currently evaluating sphinx-js for documenting a project using the latest TypeScript and typedoc versions and from what I can tell the project is not quite compatible with them.

As I explored the project's open pull requests I noticed some old ones left kind of abandoned and I've been wondering – are new PRs welcome? Are they likely to be reviewed?

I noticed this sphinx-js fork https://github.com/pyodide/sphinx-js that has some of the fixes applied but I'd like to stick to the upstream as much as possible.

**Comment by willkg** [comment]
Hi! Sorry for the lateness on this. I'm a maintainer of this project. I inherited it, but I don't use it. I maintain a bunch of other projects and am generally burned out and overwhelmed.

While I know a bunch about Sphinx extensions in general, I don't know much about documenting JavaScript/TypeScript. Generally, I've worked on changes as they're needed by Mozilla. When I did the maintenance pass I did last year, I fixed some issues Mozilla had and then looked at a bunch of other things and included them as I was able. I haven't done a maintenance pass on this since we did the release a little under a year ago.

I don't know anything about the pyodide fork--no one ever approached us about forking as far as I'm aware. I do recognize the concern about the future of this project and the need to make clear what the status is.

I'll spend some time figuring out what the future is for this project. It'll probably take me a week or two.

**Comment by raucao** [comment]
Thank you, @willkg!

May I add for consideration that well over 500 repositories [depend on this project](https://github.com/mozilla/sphinx-js/network/dependents), so it would truly be fantastic if a budget at Mozilla would allow for such a "maintenance pass" once a quarter or twice a year perhaps. It would really be helping the open-source Web ecosystem!

**Comment by willkg** [comment]
We worked out the future of the project. We're transferring it to @hoodmane who will maintain it going forward.

I opened up issue #233 to cover the transfer.

**Comment by jstasiak** [comment]
Thank you so much for your responses and thoughtful handling of the situation @willkg – it's a tough subject and I think the solution is good for everyone.

Appreciate all your work on the project.
