### ISSUE TITLE
Impossible to have empty string default values for parameters.

### ISSUE THREAD

**Issue by chrismurf** [mozilla/sphinx-js#63]
Hi,
  I have a string parameter with a default value of the empty string. but there seems to be no way to define that.  I am using JSDoc v3.5.5 and Sphinx 1.7.2.

```javascript
/**
 * @param {string} [test=] - results in a parameter named 'test='
 * @param {string} [test= ] - results in a parameter named 'test='
 * @param {string} [test=''] - results in a default value of "''"
 * @param {string} [test=""] - results in a default value of "\"\""
 */
```

**Comment by erikrose** [comment]
I agree with you. It seems to be a limitation of JSDoc itself: its JSON output (`jsdoc -X`) just ignores the existence of a default, like so:

```json
        "params": [
            {
                "optional": true,
                "name": "num",
                "defaultvalue": 5
            },
            {
                "optional": true,
                "name": "str"
            },
```

Its native HTML-rendered output just displays a blank cell. I suppose some people might read that as an empty string, though it displays the same thing if you specify `undefined`. At least it's consistent with their (ambiguous) in-doclet syntax of not taking quotes around default values.

What if we reasoned from the type? For example, if a param is declared as a string and as optional but no default is in the JSON, we reason that it must be an empty string. However, if the coder specifies `undefined`, it will look the same to us. I hoped that saying `[str=undefined]` in the doclet would work, but JSDoc seems to not extract a default from that at all. If it did, then we could reason out a "" as I proposed and force people to use the doclet to document undefineds. But since it doesn't, I think this is untractable at the sphinx-js level; we need to file an issue against JSDoc.

It's a regrettable bug, as I imagine this is a pretty common case. I'm sorry to conclude you're stuck documenting it in prose for now.

**Comment by chrismurf** [comment]
At the moment I'm using a single quote as the value, because you have to look _really close_ to see that "'" isn't the empty string with many fonts...  Yes I feel suitably horrible about doing that.

I agree it's worth filing upstream, but have little experience with JSDoc (I'm coming from the python side, and Sphinx-JS was actually my intro to it).  Do you mind filing upstream, given your background with it?

Thank you for looking into this.

**Comment by erikrose** [comment]
Upstreamed!

**Comment by erikrose** [comment]
The issue is still open on their end. I bet it will be automatically fixed here when they fix it there.
